name: vllm-rbln / PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  # Build only when a review APPROVES a PR into dev.
  build-vllm-rbln-wheel:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'dev' }}
    uses: ./.github/workflows/rbln_trigger_internal_test.yaml
    secrets: inherit
    with:
      ref: ${{ github.event.pull_request.head.sha }}
